In [1]:
!pip install sympy
import numpy as np
from sympy import Matrix

# 1. Create a dummy dataset (4 features, 5 samples)
# Feature 0: Random data
# Feature 1: Random data
# Feature 2: Redundant (Feature 0 + Feature 1)
# Feature 3: Random data
np.random.seed(42)
f0 = np.random.randint(1, 10, size=(5, 1))
f1 = np.random.randint(1, 10, size=(5, 1))
f2 = f0 + f1  # Purely redundant feature!
f3 = np.random.randint(1, 10, size=(5, 1))

# Combine into a single matrix A (Shape: 5x4)
A = np.hstack([f0, f1, f2, f3]).astype(float)
feature_names = ["Age", "Income", "Debt", "Spending_Score"]

print("--- Original Dataset Matrix A ---")
print(A)
print(f"Features: {feature_names}\n")

# 2. Compute the RREF to get the Matrix R and find pivot columns
# sympy.Matrix.rref() returns (rref_matrix, pivot_column_indices)
sympy_A = Matrix(A)
R_sympy, pivots = sympy_A.rref()

# Convert sympy Matrix R_sympy back to numpy array
R = np.array(R_sympy).astype(float)

# 3. Construct Matrix C using the exact pivot columns from A
C = A[:, pivots]

print("--- Matrix C (Core Independent Features) ---")
print(C)
print(f"Kept Independent Features: {[feature_names[i] for i in pivots]}\n")

print("--- Matrix R (The Recipes / Dependencies) ---")
print(R)
print(f"Pivot Column Indices: {pivots}\n")

# 4. Drop the redundant features
all_indices = set(range(A.shape[1]))
pivot_indices = set(pivots)
redundant_indices = list(all_indices - pivot_indices)

print("--- Dimensionality Reduction Summary ---")
for idx in redundant_indices:
    print(
        f"❌ Deleting feature '{feature_names[idx]}' (Column {idx}) because it is redundant."
    )

# Slice matrix A to only keep the independent features
reduced_A = A[:, pivots]
reduced_feature_names = [feature_names[i] for i in pivots]

print("\n--- Final Reduced Dataset ---")
print(reduced_A)
print(f"Remaining Features: {reduced_feature_names}")

--- Original Dataset Matrix A ---
[[ 7.  3. 10.  8.]
 [ 4.  7. 11.  8.]
 [ 8.  8. 16.  3.]
 [ 5.  5. 10.  6.]
 [ 7.  4. 11.  5.]]
Features: ['Age', 'Income', 'Debt', 'Spending_Score']

--- Matrix C (Core Independent Features) ---
[[7. 3. 8.]
 [4. 7. 8.]
 [8. 8. 3.]
 [5. 5. 6.]
 [7. 4. 5.]]
Kept Independent Features: ['Age', 'Income', 'Spending_Score']

--- Matrix R (The Recipes / Dependencies) ---
[[1. 0. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Pivot Column Indices: (0, 1, 3)

--- Dimensionality Reduction Summary ---
❌ Deleting feature 'Debt' (Column 2) because it is redundant.

--- Final Reduced Dataset ---
[[7. 3. 8.]
 [4. 7. 8.]
 [8. 8. 3.]
 [5. 5. 6.]
 [7. 4. 5.]]
Remaining Features: ['Age', 'Income', 'Spending_Score']
